Output ../docs/img/intro.gif
Set Theme "ayu_light"
Set FontSize 21
Set Width 1280
Set Height 800
Hide
Type "cd ../src && npx nbb ./bases/ink.cljs ghp"
Enter
Sleep 1s
Show
Sleep 3s
Type@111ms "Today I woke up"
Sleep 1s
Ctrl+Space
Sleep 1s
Type "next"
Sleep 1s
Enter
Sleep 1s
Type@111ms "A crow flew by my ear"
Enter
Type@180ms "A moment of fear"
Backspace
Sleep 1s
Type@111ms "care"
Enter
Type@140ms "We all want to feel safe."
Sleep 1s
Ctrl+Space
Sleep 1s
Type "next"
Enter
Sleep 1s
Type@222ms "I exist within a much larger web than I could imagine."
Sleep 4s
Ctrl+Space
Sleep 1s
Type "save"
Sleep 1s
Enter
Sleep 1s
