Output ./july-10.gif
Set Theme "ayu_light"
Set FontSize 21
Set Width 1280
Set Height 800
Hide
Type "cd ../src && npx nbb ./bases/ink.cljs markdown"
Enter
Sleep 1s
Show
Sleep 3s
Type@111ms "Your *favourite editor's*"
Sleep 1s
Ctrl+Space
Sleep 1s
Type "add markdown"
Sleep 1s
Enter
Sleep 1s
Type@111ms "favourite editor"
Sleep 1s
Backspace
Sleep 1s
Backspace
Sleep 1s
Type@111ms " very favourite editor"
Sleep 1s
Ctrl+Space
Sleep 1s
Type "save"
Sleep 1s
Enter
Sleep 4s
