(ns instaparse.util)

;; Both appear to be called with several strings as separate
;; arguments:
(defn throw-runtime-exception
  [& message]
  (let [^String text (apply str message)]
    (-> text
                RuntimeException. 
        throw)))

(defn throw-illegal-argument-exception
  [& message]
  (let [^String text (apply str message)]
    (-> text
                IllegalArgumentException. 
        throw)))

        
                           
                
                                   
                                  
                                   

;;;;;;;;;;;; This file autogenerated from src\instaparse\util.cljc
